name: Generate ascii artwork

on:
  push
jobs:
  ascii_job:
  runs-on: ubuntu-latest
  steps:
  - name: checkout Repo
    uses: actions/checkout@v4.1.4

  - name: Install cowsay program
    run: sudo apt-get install cowsay -y

  - name: Execute cowsay CMD
    run: cowsay -f dragon "Run for cowsay, I am a DRAGON...RAWR" >> dragon.txt

  - name: Test file Exists
    run: grep -i "dragon" dragon.txt

  - name: Read file
    run: cat dragon.txt

  - name: List Repo Files
    run: ls -ltra