name: Generate ascii artwork

on:
  push
jobs:
  ascii_job:
  runs-on: ubuntu-latest
  steps:
  - name: checkout Repo
    uses: actions/checkout@v4.1.4

  - name: List Repo Files
    run: ls -ltra

  - name: Executing shell Script
    run: ./ascii-script.sh

  